<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Active' => '',
    'Add' => '',
    'Admin' => '',
    'Are you sure you want to delete this item?' => '',
    'Backend' => '',
    'Body' => '',
    'Change avatar via {gravatar}' => '',
    'Check your email for further instructions.' => '',
    'Contact' => '',
    'Create' => '',
    'Create User' => '',
    'Created at' => '',
    'Delete' => '',
    'Email' => '',
    'Follow the link below to reset your password' => '',
    'Frontend' => '',
    'Full name' => '',
    'Hello' => '',
    'Here you can change all your account details.' => '',
    'If you forgot your password you can {reset_it}.' => '',
    'Inactive' => '',
    'Incorrect email or password.' => '',
    'Incorrect username or password.' => '',
    'Last update: <strong>{0, date}</strong>' => '',
    'Leave this field empty if you do NOT want to change the password' => '',
    'Login' => '',
    'Logout' => '',
    'Logout ({full_name})' => '',
    'Manage account' => '',
    'Member since: <strong>{0, date}</strong>' => '',
    'Name' => '',
    'New password' => '',
    'New password was saved.' => '',
    'Password' => '',
    'Password reset for {app}' => '',
    'Password reset token cannot be blank.' => '',
    'Please choose your new password.' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Please fill out the following fields to login.' => '',
    'Please fill out the following fields to signup.' => '',
    'Please fill out the following form to contact us. Thank you.' => '',
    'Please fill out your email. A link to reset password will be sent there.' => '',
    'Remember me' => '',
    'Request password reset' => '',
    'Reset' => '',
    'Reset filters' => '',
    'Reset password' => '',
    'Role' => '',
    'Save' => '',
    'Send' => '',
    'Signup' => '',
    'Sorry, we are unable to reset password for email provided.' => '',
    'Status' => '',
    'Subject' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'The requested page does not exist.' => '',
    'The role value is not valid' => '',
    'The status value is not valid' => '',
    'There is no user with such email.' => '',
    'There was an error sending email.' => '',
    'This email address has already been taken.' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated at' => '',
    'User' => '',
    'Users' => '',
    'Verification code' => '',
    'Wrong password reset token.' => '',
    'Your account has been successfully updated.' => '',
    'Home' => 'Αρχική',
];
